apiVersion: parseable.io/v1beta1
kind: ParseableTenant

metadata:
  name: parseable

spec:

  nodes:
    - name: parseable-ingestion-1
      type: server
      kind: Deployment
      replicas: 1
      k8sConfig: parseable-ingestion-1
      parseableConfig: parseable-server-config
    
    - name: parseable-ingestion-2
      type: server
      kind: Deployment
      replicas: 1
      k8sConfig: parseable-ingestion-2
      parseableConfig: parseable-server-config

  deploymentOrder:
    - server

  k8sConfig:
    - name: parseable-ingestion-1
      image: parseable/parseable:edge-debug
      service:
        type: ClusterIP
        ports:
          - protocol: TCP
            port: 80
            targetPort: 8000
      volumes:
        - emptyDir: {}
          name: stage-volume
        - emptyDir: {}
          name: data-volume
      volumeMount:
        - mountPath: /parseable/data
          name: data-volume
        - mountPath: /parseable/staging
          name: stage-volume
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
    
    - name: parseable-ingestion-2
      image: parseable/parseable:edge-debug
      service:
        type: ClusterIP
        ports:
          - protocol: TCP
            port: 80
            targetPort: 8000
      volumes:
        - emptyDir: {}
          name: stage-volume
        - emptyDir: {}
          name: data-volume
      volumeMount:
        - mountPath: /parseable/data
          name: data-volume
        - mountPath: /parseable/staging
          name: stage-volume
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi

  parseableConfig:
    - name: parseable-server-config
      cliArgs: 
        - s3-store
      env:
        P_ADDR: "0.0.0.0:8000"
        P_USERNAME: "admin"
        P_PASSWORD: "admin"
        P_STAGING_DIR: "/parseable/staging"
        P_S3_URL: "http://minio.minio.svc.cluster.local:9000"
        P_S3_ACCESS_KEY: "minioadmin"
        P_S3_SECRET_KEY: "minioadmin"
        P_S3_BUCKET: "parseable"
        P_S3_REGION: "us-east-1"
