apiVersion: parseable.io/v1beta1
kind: ParseableTenant
metadata:
  name: parseable
spec:
  nodes:
    - name: parseable-server
      kind: Deployment
      replicas: 1
      nodeType: server
      cliArgs: 
      - local-store
      k8sConfigGroup: k8s-server
      parseableConfigGroup: server-config
  deploymentOrder:
  - server
  k8sConfigGroup:
  - name: k8s-server
    image: parseable/parseable:v0.3.0
    volumes:
    - emptyDir: {}
      name: stage-volume
    - emptyDir: {}
      name: data-volume
    volumeMount:
      - mountPath: /parseable/data
        name: data-volume
      - mountPath: /parseable/staging
        name: stage-volume
  parseableConfigGroup:
  - name: server-config
    data: |-
      P_ADDR=0.0.0.0:8000 
      P_STAGING_DIR=./staging
      P_FS_DIR=./data
      P_USERNAME=admin
      P_PASSWORD=admin
