apiVersion: parseable.io/v1beta1
kind: ParseableTenant

metadata:
  name: parseable

spec:

  nodes:
    - name: parseable-small
      type: server
      kind: Deployment
      replicas: 1
      k8sConfig: parseable-server-small
      parseableConfig: parseable-server-config

    - name: parseable-medium
      type: server
      kind: Deployment
      replicas: 1
      k8sConfig: parseable-server-medium
      parseableConfig: parseable-server-config

  deploymentOrder:
    - server

  k8sConfig:
    - name: parseable-server-small
      image: parseable/parseable:v0.4.0
      service:
        name: parseable-server-small
        type: ClusterIP
        ports:
          - protocol: TCP
            port: 80
            targetPort: 8000
      volumes:
        - emptyDir: {}
          name: stage-volume
        - emptyDir: {}
          name: data-volume
      volumeMount:
        - mountPath: /parseable/data
          name: data-volume
        - mountPath: /parseable/staging
          name: stage-volume
      resources: 
        limits:
          cpu: 100m
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 2Gi

    - name: parseable-server-medium
      image: parseable/parseable:v0.4.0
      service:
        name: parseable-server-medium
        type: ClusterIP
        ports:
          - protocol: TCP
            port: 80
            targetPort: 8000
      volumes:
        - emptyDir: {}
          name: stage-volume
        - emptyDir: {}
          name: data-volume
      volumeMount:
        - mountPath: /parseable/data
          name: data-volume
        - mountPath: /parseable/staging
          name: stage-volume
      resources: 
        limits:
          cpu: 100m
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 4Gi

  parseableConfig:
    - name: parseable-server-config
      cliArgs: 
        - local-store
      env: |-
        P_ADDR=0.0.0.0:8000 
        P_STAGING_DIR=./staging
        P_FS_DIR=./data
        P_USERNAME=admin
        P_PASSWORD=admin
