{{- $env := .Values.env }}
{{- if and ($env.WATCH_NAMESPACE) (ne $env.WATCH_NAMESPACE "default") }}
# Split WATCH_NAMESPACE by commas and loop on them
{{- $watchedNamespaces := (split "," $env.WATCH_NAMESPACE) -}}
{{- range $watchedNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ . }}
  name: {{ template "parseable-operator.fullname" $ }}
  labels:
    {{- include "parseable-operator.labels" $ | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - get
    - list
    - patch
    - watch
- apiGroups:
    - ""
  resources:
    - persistentvolumeclaims
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - statefulsets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - parseable.io
  resources:
    - parseabletenants
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - parseable.io
  resources:
    - parseabletenants/status
  verbs:
    - get
    - patch
    - update
{{- end }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "parseable-operator.fullname" . }}-manager-role
rules:
{{- if and ($env.WATCH_NAMESPACE) (ne $env.WATCH_NAMESPACE "default") }}
{{- else }}
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - get
    - list
    - patch
    - watch
- apiGroups:
    - ""
  resources:
    - persistentvolumeclaims
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - statefulsets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - parseable.io
  resources:
    - parseabletenants
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - parseable.io
  resources:
    - parseabletenants/status
  verbs:
    - get
    - patch
    - update
{{- end }}

{{- $operatorName := (include "parseable-operator.fullname" .) -}}
{{- if and ($env.WATCH_NAMESPACE) (ne $env.WATCH_NAMESPACE "default") }}
# Split WATCH_NAMESPACE by commas and loop on them
{{- $watchedNamespaces := (split "," $env.WATCH_NAMESPACE) -}}
{{- range $watchedNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ . }}
  name: {{ $operatorName }}
  labels:
    {{- include "parseable-operator.labels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "parseable-operator.fullname" $ }}
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ $operatorName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "parseable-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: parseable-operator
    app.kubernetes.io/part-of: parseable-operator
  name: {{ include "parseable-operator.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "parseable-operator.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "parseable-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
