---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "parseable-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: parseable-operator
    app.kubernetes.io/part-of: parseable-operator
  name: {{ include "parseable-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
